### ISSUE TITLE
make sshpass requirement optional

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/brigade#22]
Two options:

1. Make it so it's only necessary if password based auth is enabled.
2. Use paramiko.

**Comment by ogenstad** [comment]
I would vote for a pure Python version. Either with sftp from Paramiko or with the scp module (https://github.com/jbardin/scp.py) which is already installed with netmiko. 

A problem with the scp module though is that the transfers are quite slow.

**Comment by ogenstad** [comment]
This could be closed now.

**Comment by dbarrosop** [comment]
sshpass is no longer needed
